const dataLoginpet = require("../../fixtures/loginpet.json")
describe('petstore', () => {
    beforeEach(() => {
        cy.visit('https://petstore.octoperf.com/actions/Account.action')
    })
    it('tc-01', () => {
        cy.loginpet(dataLoginpet.username.negative, dataLoginpet.password.positive)
        cy.get('li').contains('Invalid username or password. Signon failed.')
    })
    it('tc-02', () => {
        cy.loginpet(dataLoginpet.username.positive, dataLoginpet.password.negative)
        cy.get('li').contains('Invalid username or password. Signon failed.')
    })
    it('tc-03', () => {
        cy.loginpet(dataLoginpet.username.positive, dataLoginpet.password.positive)
        cy.get('#WelcomeContent').contains('Welcome ABC!')
        cy.get('#SidebarContent > [href="/actions/Catalog.action?viewCategory=&categoryId=FISH"] > img').click()
        cy.get('h2').contains('Fish')
        cy.get('tbody > :nth-child(2) > :nth-child(1) > a').click()
        cy.get(':nth-child(2) > :nth-child(5) > .Button').click()
        cy.get('#BackLink > a').click()
        cy.get('#SidebarContent > [href="/actions/Catalog.action?viewCategory=&categoryId=DOGS"] > img').click()
        cy.get('tbody > :nth-child(4) > :nth-child(1) > a').click()
        cy.get(':nth-child(2) > :nth-child(5) > .Button').click()
        cy.get('#BackLink > a').click()
        cy.get('#SidebarContent > [href="/actions/Catalog.action?viewCategory=&categoryId=CATS"] > img').click()
        cy.get('tbody > :nth-child(2) > :nth-child(1)').click()
        cy.get(':nth-child(2) > :nth-child(5) > .Button').click()
        cy.get('#BackLink > a').click()
        cy.get('#SidebarContent > [href="/actions/Catalog.action?viewCategory=&categoryId=REPTILES"] > img').click()
        cy.get('tbody > :nth-child(2) > :nth-child(1) > a').click()
        cy.get('#BackLink > a').click()
        cy.get(':nth-child(3) > :nth-child(1) > a').click()
        cy.get('.Button').click()
        cy.get('#BackLink > a').click()
        cy.get('#SidebarContent > [href="/actions/Catalog.action?viewCategory=&categoryId=BIRDS"] > img').click()
        cy.get('tbody > :nth-child(2) > :nth-child(1) > a').click()
        cy.get('.Button').click()
        cy.get(':nth-child(2) > :nth-child(5) > input').clear()
        cy.get(':nth-child(2) > :nth-child(5) > input').type('5')
        cy.get('[colspan="7"] > input').click()
        cy.get(':nth-child(6) > :nth-child(8) > .Button').click()
        cy.get('[href="/actions/Order.action?newOrderForm="]').click()
        cy.get('[name="newOrder"]').click()
        cy.get('.Button').click()
    })
    it('tc-04', () => {
        cy.loginpet(dataLoginpet.username.positive, dataLoginpet.password.positive)
        cy.get('#WelcomeContent').contains('Welcome ABC!')
        cy.get('[size="14"]').type('Fish')
        cy.get('[name="searchProducts"]').click()
        cy.get('[size="14"]').clear()
        cy.get('[size="14"]').type('Dog')
        cy.get('[name="searchProducts"]').click()
        cy.get('#LogoContent > a > img').click()
        cy.get('[href="/actions/Account.action?editAccountForm="]').click()
        cy.get('[name="editAccount"]').click()
        cy.get('[href="/actions/Account.action?signoff="]').click()
        cy.get('#MainImageContent > img')
    })
    it('tc-05', () => {
        cy.get('#Catalog > a').click()
        cy.get('[name="username"]').type('Kaen')
        cy.get(':nth-child(2) > tbody > :nth-child(2) > :nth-child(2) > input').type('1234')
        cy.get(':nth-child(2) > tbody > :nth-child(3) > :nth-child(2) > input').type('1234')
        cy.get(':nth-child(4) > tbody > :nth-child(1) > :nth-child(2) > input').type('Kongkeart')
        cy.get(':nth-child(4) > tbody > :nth-child(2) > :nth-child(2) > input').type('Narakulmongkol')
        cy.get(':nth-child(4) > tbody > :nth-child(3) > :nth-child(2) > input').type('kongkeart@gmail.com')
        cy.get(':nth-child(4) > tbody > :nth-child(4) > :nth-child(2)').type('0873961801')
        cy.get(':nth-child(5) > :nth-child(2) > input').type('test')
        cy.get(':nth-child(6) > :nth-child(2) > input').type('test2')
        cy.get(':nth-child(7) > :nth-child(2) > input').type('da')
        cy.get(':nth-child(8) > :nth-child(2) > input').type('dsa')
        cy.get(':nth-child(9) > :nth-child(2) > input').type('dsaw')
        cy.get(':nth-child(10) > :nth-child(2) > input').type('Hatyai')
        cy.get(':nth-child(2) > :nth-child(2) > select').select('DOGS')
        cy.get('[name="newAccount"]').click()
        cy.go('back')
        cy.get('#LogoContent > a > img').click()

    })
    it('tc-06', () => {
        cy.get('#LogoContent > a > img').click()
        cy.get('#QuickLinks > [href="/actions/Catalog.action?viewCategory=&categoryId=DOGS"] > img').click()
        cy.get('tbody > :nth-child(2) > :nth-child(1) > a').click()
        cy.get(':nth-child(2) > :nth-child(5) > .Button').click()
        cy.get('[href="/actions/Order.action?newOrderForm="]').click()
        cy.get('li').contains('You must sign on before attempting to check out. Please sign on and try checking out again.')
    })
})